### ISSUE TITLE
Scriptlet not Found

### ISSUE THREAD

**Issue by marcomanalo** [xored/rcptt#19]
I can run my custom ecl command using 2.4.2 RCPTT IDE. It's working last time. I just rebuild my commands. I haven't updated anything in it. Its used to work with 2.4.2 last week but when i rebuild my command it doesn't work anymore. I tried building this example commands here https://github.com/xored/rcptt.extensions.ecl. Its the same problem. They dont work anymore. It says Scriptlet not Found. I didn't modify the examples also.

**Comment by marcomanalo** [comment]
Mentioning @DudaevAR  @basilevs for this issue

**Comment by basilevs** [comment]
Please attach AUT's error log.

**Comment by marcomanalo** [comment]
Fixed https://github.com/xored/rcptt.extensions.ecl/commit/1ef17ccd34e5190cfd6e1dbb723aa55ebd254050
